name: Run backend Python tests

on:
  push:
    branches:
      - "backend"
  pull_request:
    branches:
      - "backend"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11]

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2
        # Setup which version of Python to use
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        # Install the package using the setup.py
        working-directory: backend
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
        working-directory: backend
        # Install pytest (you can use some other testing utility)
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        working-directory: backend
        # Run the tests. I'm using pytest and the file is in the tests directory.
      - name: Run tests
        run: python -m pytest -v
        working-directory: backend

